version: '3.9'
services:
  web:
    build: .
    restart: always
    environment:
      - NOTION_KEY=${NOTION_KEY}
      - NOTION_DATABASE_ID=${NOTION_DATABASE_ID}
      - PORT=80
    volumes:
      - /home/root/bitwarden/data:/data
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.bitwarden.entrypoints=web'
      - 'traefik.http.routers.bitwarden.rule=Host(`apple-shortcut-create-notion-todo.zetkin.4lus.de`)' ## Hier anpassen ##
      - 'traefik.http.routers.bitwarden.middlewares=redirect@file'
      - 'traefik.http.routers.bitwarden-secured.entrypoints=web-secured'
      - 'traefik.http.routers.bitwarden-secured.rule=Host(`apple-shortcut-create-notion-todo.zetkin.4lus.de`)' ## Hier anpassen ##
      - 'traefik.http.routers.bitwarden-secured.tls.certresolver=mytlschallenge'
    networks:
      - web

networks:
  web:
    external: true
